# See pkg-message in https://www.freshports.org/multimedia/webcamd/

- name: "Ensure 'cuse' kernel module is loaded"
  ansible.builtin.command: kldload -n cuse
  become: true
  become_user: root
  register: loaded
  changed_when: false
  failed_when: loaded.rc > 0

- name: "Set 'cuse' kernel module to load at boot in {{ cfg_webcam_freebsd_loader_conf_path }}"
  community.general.sysrc:
    path: "{{ cfg_webcam_freebsd_loader_conf_path }}"
    name: "cuse_load"
    value: "YES"
    state: present
  become: true
  become_user: root

