- name: "Export vars for other roles to use"
  ansible.builtin.include_tasks: export_vars.yml

- name: "Install and configure webcam services"
  ansible.builtin.include_tasks: services.yml

- name: "Install and configure webcam kernel modules"
  ansible.builtin.include_tasks: kernel_mods.yml

- name: "Configure video-4-linux compatibility layer"
  ansible.builtin.include_tasks: video_4_linux.yml

